// Code generated by "stringer -type=TokenModifier -linecomment"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenModifierDeclaration-0]
	_ = x[tokenModifierCount-1]
}

const _TokenModifier_name = "declaration-count-"

var _TokenModifier_index = [...]uint8{0, 11, 18}

func (i TokenModifier) String() string {
	if i < 0 || i >= TokenModifier(len(_TokenModifier_index)-1) {
		return "TokenModifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenModifier_name[_TokenModifier_index[i]:_TokenModifier_index[i+1]]
}
