// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Bool-1]
	_ = x[Int-2]
	_ = x[Int8-3]
	_ = x[Int16-4]
	_ = x[Int32-5]
	_ = x[Int64-6]
	_ = x[Float32-7]
	_ = x[Float64-8]
	_ = x[Byte-9]
	_ = x[Bytes-10]
	_ = x[String-11]
	_ = x[Any-12]
	_ = x[Map-13]
	_ = x[Vector-14]
	_ = x[Array-15]
	_ = x[Enum-16]
	_ = x[Struct-17]
	_ = x[Interface-18]
}

const _Kind_name = "InvalidBoolIntInt8Int16Int32Int64Float32Float64ByteBytesStringAnyMapVectorArrayEnumStructInterface"

var _Kind_index = [...]uint8{0, 7, 11, 14, 18, 23, 28, 33, 40, 47, 51, 56, 62, 65, 68, 74, 79, 83, 89, 98}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
