//go:build ignore

// usage: go run gendoc.go -o doc.go

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"

	"github.com/next/next/src/grammar"
)

var filename = flag.String("o", "doc.go", "The filename to write the default API documentation to.")

func main() {
	flag.Parse()

	// Generate the default API
	content, err := json.MarshalIndent(grammar.Default, "//\t", "  ")
	if err != nil {
		panic(err)
	}
	os.WriteFile(*filename, []byte(fmt.Sprintf(`// Code generated by gendoc.go; DO NOT EDIT.

package grammar

// @api(Grammar.default) represents the default grammar for the next files.
//
//	<details>
//	<summary>default-grammar.json</summary>
//
//	%s
//	%s
//	%s
//	</details>
`, "```json", string(content), "```")), 0644)
}
