import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    "overview",
    "installation",
    {
      type: "category",
      label: "Guides",
      link: {
        type: "generated-index",
        title: "Next Guides",
        description: "Let's learn about the most important Next concepts!",
        keywords: ["guides"],
      },
      collapsed: false,
      collapsible: false,
      items: [
        "guides/language_guide",
        "guides/annotation_guide",
        "guides/template_guide",
      ],
    },
    "language_spec",
    "downloads",
  ],

  api: [{ type: "autogenerated", dirName: "api" }],

  showcase: [{ type: "autogenerated", dirName: "showcase" }],
};

export default sidebars;
