name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Next ${{ github.ref_name }}
          draft: false
          prerelease: false

  release:
    name: Release for Linux and macOS
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build and Create Tar.gz
        run: make release

      - name: Upload Tar.gz to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: build/next*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_windows:
    name: Release for Windows
    env:
      GITHUB_REF_NAME: ${{ github.ref_name }}
      GITHUB_SHA: ${{ github.sha }}
    needs: create_release
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Make
        shell: pwsh
        run: |
          choco install make -y
          echo 'C:\ProgramData\chocolatey\lib\make\tools\bin' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build Windows Executable and Create MSI Package
        shell: pwsh
        run: make release/windows

      - name: Upload MSI to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: build/next*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
